### PR TITLE
Compile ps-client for browser

### PR DESCRIPTION
**Pull request by singiamtel**
Had to change ``inline-css`` for ``juice`` as it didn't compile through browserify properly, but it seems to work fine

### CODE REVIEW

**Review by PartMan7 — COMMENTED** [review]
Looks good from a first glance; will test and get back

**Comment by PartMan7** [comment]
Hi have completed lightning-fast tests

**Comment by singiamtel** [comment]
I'm not sure if it's working properly even if it compiles tbh, I think we should scrap this

**Comment by PartMan7** [comment]
Need to run in the browser once, but the juice change in particular is appreciated

**Comment by singiamtel** [comment]
> Need to run in the browser once, but the juice change in particular is appreciated

@PartMan7 I don't think the browser side of the PR is ready to be merged, should I close the PR? I can repurpose it to only include the juice change if you want (and fix the merge issues)

**Comment by PartMan7** [comment]
I have a local version of this checked out with planned fixes; had some weird failures there. Can push to some other branch as reference when I get home today if you'd like.

If you'd like to try doing this again on this PR that works out great too; haven't had the time to focus on fixing that.

**Comment by PartMan7** [comment]
Adopted bits of logic from here individually. Thanks! <3

**Pull request closed without merging**
